ARG JOOMLA_SOURCE_IMAGE=joomla:6.1.3-php8.4-apache
FROM ${JOOMLA_SOURCE_IMAGE} AS joomla-source

FROM php:8.5-apache@sha256:e7c4a78bc342384903c942f50329636cf9c9d0b1b51860065f443c048f260c43

RUN apt-get update \
    && apt-get install -y --no-install-recommends libbz2-dev libfreetype-dev libgmp-dev libicu-dev libjpeg62-turbo-dev libpng-dev libpq-dev libzip-dev \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j"$(nproc)" bcmath bz2 exif gd gmp intl mysqli pdo_mysql pdo_pgsql pgsql zip \
    && rm -rf /var/lib/apt/lists/*

COPY --from=joomla-source /entrypoint.sh /entrypoint.sh
COPY --from=joomla-source /makedb.php /makedb.php
COPY --from=joomla-source /usr/src/joomla /usr/src/joomla

ENTRYPOINT ["/entrypoint.sh"]
CMD ["apache2-foreground"]
