# Copyright (C) 2026 Svend Gundestrup. All Rights Reserved.
# SonarCloud Automatic Analysis configuration.
# AutoScan does not read sonar-project.properties.
# Directory paths are intentionally used instead of wildcard patterns.
sonar.exclusions=tests/,stubs/,media/,build/,vendor/,node_modules/
sonar.tests=tests/
sonar.test.exclusions=tests/
