# Copyright (C) 2026 Svend Gundestrup. All Rights Reserved.
# SonarCloud Automatic Analysis configuration.
# AutoScan does not read sonar-project.properties.
# Exclusions use glob patterns; source/test scopes use directory paths.
sonar.exclusions=tests/**,stubs/**,media/**,build/**,vendor/**,node_modules/**
sonar.tests=tests
sonar.test.exclusions=tests/**
