#!/usr/bin/env bash
# Validate the Joomla update-server stream (update.xml) and the manifest's
# <updateservers> registration. Catches the failure modes that make update
# streams silently dead: unreachable URL, wrong element/type, malformed
# download URL, missing/short hashes, or a stream ahead of VERSION.
#
# The stream may lag VERSION (it describes the latest *published* release and
# is regenerated by the update-server workflow after publish), but it must
# never be ahead of it.
#
# Usage: scripts/validate-update-xml.sh

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
XML="$REPO_ROOT/update.xml"
MANIFEST="$REPO_ROOT/administrator/manifests/packages/pkg_j2xml.xml"
EXPECTED_SERVER="https://raw.githubusercontent.com/gundestrup/j2xml/main/update.xml"

errors=0
fail() { echo "FAIL: $1" >&2; errors=$((errors + 1)); }
field() { xmllint --xpath "string($1)" "$XML" 2>/dev/null; }

command -v xmllint >/dev/null || { echo "FAIL: xmllint required (apt: libxml2-utils, brew: libxml2)" >&2; exit 1; }
[[ -f "$XML" ]] || { echo "FAIL: update.xml missing" >&2; exit 1; }
xmllint --noout "$XML" 2>/dev/null || { echo "FAIL: update.xml is not well-formed" >&2; exit 1; }

[[ "$(field /updates/update/element)" = "pkg_j2xml" ]] || fail "element must be pkg_j2xml"
[[ "$(field /updates/update/type)" = "package" ]] || fail "type must be package"
[[ "$(field /updates/update/client)" = "site" ]] || fail "client must be site — pkg_j2xml installs with client_id=0, and a client mismatch leaves the discovered update unattached (extension_id=0)"

version="$(field /updates/update/version)"
[[ "$version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || fail "version '$version' is not semver"

expected_url="https://github.com/gundestrup/j2xml/releases/download/v${version}/pkg_j2xml.zip"
[[ "$(field /updates/update/downloads/downloadurl)" = "$expected_url" ]] || fail "downloadurl does not match version/asset convention"
[[ "$(field /updates/update/infourl)" = "https://github.com/gundestrup/j2xml/releases/tag/v${version}" ]] || fail "infourl does not point at the release tag"

[[ "$(field /updates/update/sha256)" =~ ^[0-9a-f]{64}$ ]] || fail "sha256 missing or not 64 hex chars"
[[ "$(field /updates/update/sha384)" =~ ^[0-9a-f]{96}$ ]] || fail "sha384 missing or not 96 hex chars"
[[ "$(field /updates/update/sha512)" =~ ^[0-9a-f]{128}$ ]] || fail "sha512 missing or not 128 hex chars"

[[ -n "$(field /updates/update/targetplatform/@version)" ]] || fail "targetplatform missing"
[[ -n "$(field /updates/update/php_minimum)" ]] || fail "php_minimum missing"
[[ -n "$(field '/updates/update/downloads/downloadurl[not(contains(text(), " "))]')" ]] || fail "downloadurl must not contain whitespace"

# Stream must not advertise a version newer than VERSION.
repo_version="$(tr -d '[:space:]' <"$REPO_ROOT/VERSION")"
latest="$(printf '%s\n%s\n' "$version" "$repo_version" | sort -V | tail -1)"
[[ "$latest" = "$repo_version" ]] || fail "update.xml ($version) is ahead of VERSION ($repo_version)"

# The manifest must register the URL serving this file — the failure that
# made lscache-joomla's stream unreachable.
server="$(xmllint --xpath 'string(/extension/updateservers/server)' "$MANIFEST" 2>/dev/null)"
[[ "$server" = "$EXPECTED_SERVER" ]] || fail "manifest updateservers URL is '$server', expected '$EXPECTED_SERVER'"
stype="$(xmllint --xpath 'string(/extension/updateservers/server/@type)' "$MANIFEST" 2>/dev/null)"
[[ "$stype" = "extension" ]] || fail "updateservers server type must be 'extension'"

if [[ $errors -gt 0 ]]; then
    echo "update.xml validation failed ($errors error(s))" >&2
    exit 1
fi
echo "update.xml validation passed (stream at ${version}, VERSION ${repo_version})"
